;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from squish-feature.el

(add-to-list 'auto-mode-alist '("\\.feature" . squish-feature-mode))
(register-definition-prefixes "squish-feature" '("squish-feature-"))


;;; Generated autoloads from squishrunner.el

(register-definition-prefixes "squishrunner" '("squish"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
